services:
  postgres:
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_DB: geodata
      POSTGRES_USER: geoagent
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  db_data:
