# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_basic_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(240, 60, 221, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.filterPoi = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.filterPoi.setObjectName("filterPoi")
        self.filterPoiCB = QtWidgets.QComboBox(self.filterPoi)
        self.filterPoiCB.setGeometry(QtCore.QRect(10, 30, 91, 22))
        self.filterPoiCB.setObjectName("filterPoiCB")
        self.filterPoiApplyBTN = QtWidgets.QPushButton(self.filterPoi)
        self.filterPoiApplyBTN.setGeometry(QtCore.QRect(140, 90, 61, 23))
        self.filterPoiApplyBTN.setObjectName("filterPoiApplyBTN")
        self.filterPoiLE = QtWidgets.QLineEdit(self.filterPoi)
        self.filterPoiLE.setGeometry(QtCore.QRect(110, 30, 101, 20))
        self.filterPoiLE.setObjectName("filterPoiLE")
        self.gridLayout.addWidget(self.filterPoi, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 221, 131))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.countrySelect = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.countrySelect.setObjectName("countrySelect")
        self.countrySelectCB = QtWidgets.QComboBox(self.countrySelect)
        self.countrySelectCB.setGeometry(QtCore.QRect(10, 20, 131, 22))
        self.countrySelectCB.setObjectName("countrySelectCB")
        self.countrySelectBTN = QtWidgets.QPushButton(self.countrySelect)
        self.countrySelectBTN.setGeometry(QtCore.QRect(150, 20, 61, 23))
        self.countrySelectBTN.setObjectName("countrySelectBTN")
        self.gridLayout_2.addWidget(self.countrySelect, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(470, 60, 221, 131))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SaveResults = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.SaveResults.setObjectName("SaveResults")
        self.saveResultsTab = QtWidgets.QTabWidget(self.SaveResults)
        self.saveResultsTab.setGeometry(QtCore.QRect(6, 19, 211, 111))
        self.saveResultsTab.setObjectName("saveResultsTab")
        self.saveShapeTab = QtWidgets.QWidget()
        self.saveShapeTab.setObjectName("saveShapeTab")
        self.createNewShapefileBTN = QtWidgets.QPushButton(self.saveShapeTab)
        self.createNewShapefileBTN.setGeometry(QtCore.QRect(0, 60, 111, 23))
        self.createNewShapefileBTN.setObjectName("createNewShapefileBTN")
        self.shapeSaveFileNameLE = QtWidgets.QLineEdit(self.saveShapeTab)
        self.shapeSaveFileNameLE.setGeometry(QtCore.QRect(0, 10, 151, 20))
        self.shapeSaveFileNameLE.setObjectName("shapeSaveFileNameLE")
        self.shapeOpenFilePathTB = QtWidgets.QToolButton(self.saveShapeTab)
        self.shapeOpenFilePathTB.setGeometry(QtCore.QRect(160, 10, 25, 19))
        self.shapeOpenFilePathTB.setObjectName("shapeOpenFilePathTB")
        self.shapeSaveFieldCB = QtWidgets.QComboBox(self.saveShapeTab)
        self.shapeSaveFieldCB.setGeometry(QtCore.QRect(0, 30, 121, 22))
        self.shapeSaveFieldCB.setObjectName("shapeSaveFieldCB")
        self.shapeSaveBTN = QtWidgets.QPushButton(self.saveShapeTab)
        self.shapeSaveBTN.setGeometry(QtCore.QRect(140, 30, 61, 23))
        self.shapeSaveBTN.setObjectName("shapeSaveBTN")
        self.saveResultsTab.addTab(self.saveShapeTab, "")
        self.saveCSVTab = QtWidgets.QWidget()
        self.saveCSVTab.setObjectName("saveCSVTab")
        self.csvSaveFileNameLE = QtWidgets.QLineEdit(self.saveCSVTab)
        self.csvSaveFileNameLE.setGeometry(QtCore.QRect(10, 30, 151, 20))
        self.csvSaveFileNameLE.setObjectName("csvSaveFileNameLE")
        self.csvOpenFilePathTB = QtWidgets.QToolButton(self.saveCSVTab)
        self.csvOpenFilePathTB.setGeometry(QtCore.QRect(170, 30, 25, 19))
        self.csvOpenFilePathTB.setObjectName("csvOpenFilePathTB")
        self.csvSaveBTN = QtWidgets.QPushButton(self.saveCSVTab)
        self.csvSaveBTN.setGeometry(QtCore.QRect(120, 60, 75, 23))
        self.csvSaveBTN.setObjectName("csvSaveBTN")
        self.saveResultsTab.addTab(self.saveCSVTab, "")
        self.gridLayout_3.addWidget(self.SaveResults, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 681, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.importCountryBTN = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.importCountryBTN.setObjectName("importCountryBTN")
        self.horizontalLayout_2.addWidget(self.importCountryBTN)
        self.importPoiBTN = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.importPoiBTN.setObjectName("importPoiBTN")
        self.horizontalLayout_2.addWidget(self.importPoiBTN)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 200, 561, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.customDistance = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        self.customDistance.setTitle("")
        self.customDistance.setObjectName("customDistance")
        self.label = QtWidgets.QLabel(self.customDistance)
        self.label.setGeometry(QtCore.QRect(270, 10, 41, 16))
        self.label.setObjectName("label")
        self.customLimitCB = QtWidgets.QComboBox(self.customDistance)
        self.customLimitCB.setGeometry(QtCore.QRect(500, 10, 51, 21))
        self.customLimitCB.setObjectName("customLimitCB")
        self.radiusUnitMI = QtWidgets.QRadioButton(self.customDistance)
        self.radiusUnitMI.setGeometry(QtCore.QRect(430, 10, 31, 17))
        self.radiusUnitMI.setObjectName("radiusUnitMI")
        self.radiusUnitKM = QtWidgets.QRadioButton(self.customDistance)
        self.radiusUnitKM.setGeometry(QtCore.QRect(390, 10, 41, 17))
        self.radiusUnitKM.setObjectName("radiusUnitKM")
        self.label_2 = QtWidgets.QLabel(self.customDistance)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 21, 16))
        self.label_2.setObjectName("label_2")
        self.customLatitudeLE = QtWidgets.QLineEdit(self.customDistance)
        self.customLatitudeLE.setGeometry(QtCore.QRect(50, 10, 81, 20))
        self.customLatitudeLE.setObjectName("customLatitudeLE")
        self.label_3 = QtWidgets.QLabel(self.customDistance)
        self.label_3.setGeometry(QtCore.QRect(150, 10, 31, 16))
        self.label_3.setObjectName("label_3")
        self.customLongitudeLE = QtWidgets.QLineEdit(self.customDistance)
        self.customLongitudeLE.setGeometry(QtCore.QRect(180, 10, 81, 20))
        self.customLongitudeLE.setObjectName("customLongitudeLE")
        self.label_4 = QtWidgets.QLabel(self.customDistance)
        self.label_4.setGeometry(QtCore.QRect(470, 10, 31, 16))
        self.label_4.setObjectName("label_4")
        self.customRadiusLE = QtWidgets.QLineEdit(self.customDistance)
        self.customRadiusLE.setGeometry(QtCore.QRect(310, 10, 71, 20))
        self.customRadiusLE.setObjectName("customRadiusLE")
        self.horizontalLayout_3.addWidget(self.customDistance)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(9, 620, 681, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.selectAllBTN = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.selectAllBTN.setObjectName("selectAllBTN")
        self.horizontalLayout_4.addWidget(self.selectAllBTN)
        self.invertAllBTN = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.invertAllBTN.setObjectName("invertAllBTN")
        self.horizontalLayout_4.addWidget(self.invertAllBTN)
        self.clearAllBTN = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.clearAllBTN.setObjectName("clearAllBTN")
        self.horizontalLayout_4.addWidget(self.clearAllBTN)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.RESET = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.RESET.setObjectName("RESET")
        self.horizontalLayout_4.addWidget(self.RESET)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(580, 200, 111, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchBTN = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.searchBTN.setObjectName("searchBTN")
        self.verticalLayout_2.addWidget(self.searchBTN)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 249, 681, 361))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.resultsAndMapHBL = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.resultsAndMapHBL.setContentsMargins(0, 0, 0, 0)
        self.resultsAndMapHBL.setObjectName("resultsAndMapHBL")
        self.resultsAndMapBOX = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.resultsAndMapBOX.setObjectName("resultsAndMapBOX")
        self.resultsList = QtWidgets.QListView(self.resultsAndMapBOX)
        self.resultsList.setGeometry(QtCore.QRect(5, 21, 241, 331))
        self.resultsList.setObjectName("resultsList")
        self.resultsMapWidget = QtWidgets.QWidget(self.resultsAndMapBOX)
        self.resultsMapWidget.setGeometry(QtCore.QRect(259, 9, 421, 351))
        self.resultsMapWidget.setObjectName("resultsMapWidget")
        self.resultsAndMapHBL.addWidget(self.resultsAndMapBOX)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.saveResultsTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filterPoi.setTitle(_translate("MainWindow", "Filter"))
        self.filterPoiApplyBTN.setText(_translate("MainWindow", "Apply"))
        self.countrySelect.setTitle(_translate("MainWindow", "Country"))
        self.countrySelectBTN.setText(_translate("MainWindow", "Select"))
        self.SaveResults.setTitle(_translate("MainWindow", "Save Results"))
        self.createNewShapefileBTN.setText(_translate("MainWindow", "Create New Shape"))
        self.shapeOpenFilePathTB.setText(_translate("MainWindow", "..."))
        self.shapeSaveBTN.setText(_translate("MainWindow", "Save"))
        self.saveResultsTab.setTabText(self.saveResultsTab.indexOf(self.saveShapeTab), _translate("MainWindow", "Shape"))
        self.csvOpenFilePathTB.setText(_translate("MainWindow", "..."))
        self.csvSaveBTN.setText(_translate("MainWindow", "Save"))
        self.saveResultsTab.setTabText(self.saveResultsTab.indexOf(self.saveCSVTab), _translate("MainWindow", "CSV"))
        self.importCountryBTN.setText(_translate("MainWindow", "Import Country .shp"))
        self.importPoiBTN.setText(_translate("MainWindow", "Import POI .shp"))
        self.label.setText(_translate("MainWindow", "Radius: "))
        self.radiusUnitMI.setText(_translate("MainWindow", "mi"))
        self.radiusUnitKM.setText(_translate("MainWindow", "km"))
        self.label_2.setText(_translate("MainWindow", "Lat:"))
        self.label_3.setText(_translate("MainWindow", "Long:"))
        self.label_4.setText(_translate("MainWindow", "Limit: "))
        self.selectAllBTN.setText(_translate("MainWindow", "Select All"))
        self.invertAllBTN.setText(_translate("MainWindow", "Invert"))
        self.clearAllBTN.setText(_translate("MainWindow", "Clear All"))
        self.RESET.setText(_translate("MainWindow", "RESET"))
        self.searchBTN.setText(_translate("MainWindow", "SEARCH"))
        self.resultsAndMapBOX.setTitle(_translate("MainWindow", "Results"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

